import type { Player } from './types';

export const LOCAL_PLAYER_ID = 'player-local';

export const dummyPlayers: Player[] = [
  {
    id: LOCAL_PLAYER_ID,
    username: 'You',
    avatar: '🎯',
    rank: 'gold',
    score: 18,
    isCurrentTurn: true,
    isLocalPlayer: true,
    status: 'online',
    voiceState: 'connected',
    stats: {
      gamesPlayed: 247,
      winRate: 0.58,
      currentStreak: 3,
      highestStreak: 12,
      totalRewards: 4850,
    },
    position: { x: -2.8, y: 0.5, z: 2.2 },
    color: '#3b82f6',
  },
  {
    id: 'player-2',
    username: 'NovaBlaze',
    avatar: '🔥',
    rank: 'platinum',
    score: 22,
    isCurrentTurn: false,
    isLocalPlayer: false,
    status: 'online',
    voiceState: 'speaking',
    stats: {
      gamesPlayed: 892,
      winRate: 0.64,
      currentStreak: 5,
      highestStreak: 18,
      totalRewards: 12400,
    },
    position: { x: 2.8, y: 0.5, z: 2.2 },
    color: '#ef4444',
  },
  {
    id: 'player-3',
    username: 'LuckyStar',
    avatar: '⭐',
    rank: 'silver',
    score: 15,
    isCurrentTurn: false,
    isLocalPlayer: false,
    status: 'online',
    voiceState: 'muted',
    stats: {
      gamesPlayed: 156,
      winRate: 0.51,
      currentStreak: 1,
      highestStreak: 7,
      totalRewards: 2100,
    },
    position: { x: -2.8, y: 0.5, z: -2.2 },
    color: '#eab308',
  },
  {
    id: 'player-4',
    username: 'DiceKing',
    avatar: '👑',
    rank: 'diamond',
    score: 25,
    isCurrentTurn: false,
    isLocalPlayer: false,
    status: 'online',
    voiceState: 'connected',
    stats: {
      gamesPlayed: 1543,
      winRate: 0.71,
      currentStreak: 8,
      highestStreak: 24,
      totalRewards: 28900,
    },
    position: { x: 2.8, y: 0.5, z: -2.2 },
    color: '#22c55e',
  },
];

export const aiOpponent: Player = {
  id: 'ai-bot',
  username: 'DiceBot',
  avatar: '🤖',
  rank: 'gold',
  score: 14,
  isCurrentTurn: false,
  isLocalPlayer: false,
  status: 'online',
  voiceState: 'disconnected',
  stats: {
    gamesPlayed: 9999,
    winRate: 0.55,
    currentStreak: 0,
    highestStreak: 0,
    totalRewards: 0,
  },
  position: { x: 2.8, y: 0.5, z: 0 },
  color: '#a855f7',
};
